coverage:
  status:
    project:
      default:
        target: 70%      # project-wide goal
        threshold: 1%    # allow small fluctuations
    patch:
      default:
        target: 70%
comment:
  layout: "reach, diff, files"
  behavior: default
ignore:
  - "docs/**"
  - "opensr_srgan/tests/**"
  - "opensr_srgan/tests/*"
  - "opensr_srgan/data/**"
  - "tests/**"
  - "opensr_srgan/tests/**"
