coverage:
  status:
    project:
      default:
        target: 10%      # project-wide goal
        threshold: 1%    # allow small fluctuations
    patch:
      default:
        target: 10%
comment:
  layout: "reach, diff, files"
  behavior: default
ignore:
  - "docs/**"
  - "opensr_srgan/tests/**"
  - "opensr_srgan/tests/*"
  - "opensr_srgan/data/**"
  - "opensr_srgan/data/*"
  - "tests/**"
