coverage:
  status:
    project:
      default:
        target: 80%      # project-wide goal
        threshold: 1%    # allow small fluctuations
    patch:
      default:
        target: 80%
comment:
  layout: "reach, diff, files"
  behavior: default
ignore:
  - "docs/**"
  - "examples/**"
  - "tests/**"
