# General Settings

# Data Settings
Data:
  # Loader Settings
  train_batch_size: 12 #12
  val_batch_size: 8
  num_workers: 6
  prefetch_factor: 2 #8 #2

  # Detailed Dataset Setttings
  dataset_type: 'S2_6b' # ['cv', 'SPOT6', 'S2_6b']
  data_dir: 'E:/thesis_paper/data/' # ['data/openImages/',''E:/thesis_paper/data/', '/data3/S2_20m']
  sen2_amount: 4
  spectral_matching: 'histogram'
  return_type: 'cross_sensor' #interpolated_matched


# Model, Loss, Training  Settings
Model:
  in_bands: 6
  continue_training: False # Either False or path to continue training PL Style
  load_checkpoint: False # load only weights from checkpoint - Either False or Path

Training:
  pretrain_g_only: True  # whether to pretrain G only for some steps
  g_pretrain_steps: 150000   # how many steps to pretrain G only (default: 150k)
  adv_loss_ramp_steps: 20000  #  how many intermediate adv loss steps before weight finalized (default: 20k)
  label_smoothing: True # for discrimnator labels, set True to 0.9 instead of 1.0 for 'better' gradients
  Losses:
    # --- GAN term ---
    adv_loss_beta: 1e-3       # final adv weight after ramp

    # --- Loss Term Builder ---
    # --- Pixel / Spectral / Perceptual content terms (GeneratorContentLoss) ---
    l1_weight: 1.0            # L1 over all bands
    sam_weight: 0.05          # Spectral Angle Mapper over all bands
    perceptual_weight: 0.1    # VGG(3-band) MSE
    tv_weight: 0.0            # Total variation (optional)
    # --- Quality metrics used as auxiliary losses (optional) ---
    psnr_weight: 0.0          # uses loss = -PSNR
    ssim_weight: 0.0          # uses loss = 1 - SSIM
    # --- Perceptual/metrics settings ---
    max_val: 1.0              # dynamic range for PSNR/SSIM (set to 2.0 if inputs are in [-1,1])
    ssim_win: 11              # SSIM window size (odd int)


Generator:
  model_type: 'rrdb' # ['SRResNet', 'res','rcab','rrdb','lka']
  large_kernel_size: 9
  small_kernel_size: 3
  n_channels: 96 # original 64
  n_blocks: 32 # original 16
  scaling_factor: 8

Discriminator:
  kernel_size: 3
  n_channels: 64
  n_blocks: 8
  fc_size: 1024

TruncatedVGG:
  i: 5
  j: 4

Optimizers:
  optim_g_lr: 1e-4
  optim_d_lr: 1e-4

Schedulers:
  metric: 'val_metrics/l1'
  patience_g: 100
  patience_d: 100
  factor_g: 0.5
  factor_d: 0.5
  verbose: True

Logging:
  num_val_images: 5
