site_name: SRGAN Docs
site_description: Flexible Super-Resolution GANs for satellite imagery
site_url: https://srgan.opensr.eu/
copyright: "2023-2024, Simon Donike et al."
repo_url: https://github.com/simon-donike/SISR-RS-SRGAN
repo_name: simon-donike/SISR-RS-SRGAN
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  favicon: assets/logo.png
  #favicon: assets/favicon.png
  features:
    - navigation.tabs        # <- top tabs
    - navigation.sections    # sidebar sections
    - navigation.indexes     # use section index pages (api-reference/index.md)
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.snippets:
      base_path:
        - .
        - ./docs
        - ..
      check_paths: true
      encoding: utf-8

  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.superfences

edit_uri: edit/main/docs/


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/simon-donike/SISR-RS-SRGAN
  generator: false

nav:  
  - Home:
      - Overview: index.md
      - Getting Started: getting-started.md
      - Inference Guide: inference.md
      - Architecture: architecture.md
      - Configuration: configuration.md
      - Data Preparation: data.md
      - Training Workflow: training.md
      - Trainer Details: trainer-details.md
      - Training Guideline: training-guideline.md
      - Results: results.md

  - API reference:
      - Overview: api-reference/index.md
      - Inference API: api-reference/inference.md
      - Training API: api-reference/training.md
      - Model Components: api-reference/model.md
      - Data Pipeline: api-reference/data.md
      - Utility Helpers: api-reference/utils.md