site_name: Remote-Sensing SRGAN Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
    - content.code.annotate
  palette:
    - scheme: default
      primary: teal
      accent: deep orange
repo_url: https://github.com/ESAOpenSR/Remote-Sensing-SRGAN
repo_name: ESAOpenSR/Remote-Sensing-SRGAN
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
      - Configuration: configuration.md
      - Training Workflow: training.md
      - Data Pipelines: data.md
      - Model Components: architecture.md
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
