site_name: SRGAN for Remote Sensing
site_description: Flexible super-resolution GANs for satellite imagery
site_url: https://simon-donike.github.io/SISR-RS-SRGAN/
repo_url: https://github.com/simon-donike/SISR-RS-SRGAN
repo_name: simon-donike/SISR-RS-SRGAN
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs        # <- top tabs
    - navigation.sections    # sidebar sections
    - navigation.indexes     # use section index pages (api-reference/index.md)
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
        - ./docs
        - ..
      check_paths: true
      encoding: utf-8

  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.superfences

nav:
  - Home:
      - Overview: index.md
      - Getting Started: getting-started.md
      - Inference Guide: inference.md
      - Architecture: architecture.md
      - Configuration: configuration.md
      - Data Preparation: data.md
      - Training Workflow: training.md
      - Trainer Details: trainer-details.md
      - Training Guideline: training-guideline.md
      - Results: results.md

  - API reference:
      - Overview: api-reference/index.md
      - Inference API: api-reference/inference.md
      - Training API: api-reference/training.md
      - Model Components: api-reference/model.md
      - Data Pipeline: api-reference/data.md
      - Utility Helpers: api-reference/utils.md