site_name: SRGAN for Remote Sensing
site_description: Flexible super-resolution GANs for satellite imagery
site_url: https://simon-donike.github.io/SISR-RS-SRGAN/
repo_url: https://github.com/simon-donike/SISR-RS-SRGAN
repo_name: simon-donike/SISR-RS-SRGAN
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
        - ./docs
        - ..
      check_paths: true
      encoding: utf-8

  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Configuration: configuration.md
  - Data: data.md
  - Training: training.md
  - Results: results.md
