# OpenSR packaged config for the Sentinel-2 RGB + NIR SRGAN.
Model:
  in_bands: 4

Generator:
  model_type: 'rrdb'
  large_kernel_size: 9
  small_kernel_size: 3
  n_channels: 96
  n_blocks: 32
  scaling_factor: 4

Discriminator:
  model_type: 'standard'
  n_blocks: 8

Training:
  pretrain_g_only: True
  g_pretrain_steps: 100000
  adv_loss_ramp_steps: 25000
  label_smoothing: True

  EMA:
    enabled: True
    decay: 0.999
    update_after_step: 0
    use_num_updates: True

  Losses:
    adv_loss_beta: 0.001
    adv_loss_schedule: 'cosine'
    l1_weight: 1.0
    sam_weight: 0.05
    perceptual_weight: 0.1
    perceptual_metric: 'vgg'
    tv_weight: 0.0
