# .github/workflows/ci.yml
# manual run:
# pytest -q --maxfail=1 --disable-warnings --cov=opensr_srgan  --cov-report=term-missing --cov-report=xml


name: CI Tests
on:
  push:
    tags: [ 'v*' ]    # CI only runs on tagged releases like v1.2.3


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov
          pip install --index-url https://download.pytorch.org/whl/cpu torch
          pip install -r requirements.txt
          pip install numpy

      - name: Run tests with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=opensr_srgan \
                 --cov-report=term-missing \
                 --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          verbose: true
