# .github/workflows/ci.yml
name: CI
on:
  pull_request:
    branches: [ main ]      # CI for PRs into main
  push:
    branches: [ main ]      # CI on direct pushes to main
    tags: [ 'v*' ]          # CI also runs when you push a tag like v1.2.3


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e ".[dev,test]" || pip install pytest pytest-cov
      - name: Tests + coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=opensr_srgan --cov-report=xml
      # Upload once (avoid 3 uploads from the matrix)
      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v4
        with:
          # For public repos token is optional; for private, add:
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
