name: Create GitHub Release

on:
  push:
    tags:
      - "v*"   # triggers for any tag starting with 'v'

permissions:
  contents: write  # required for creating releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
